### ISSUE TITLE
Inputs inside of a `sortable-item` are inactive

### ISSUE THREAD

**Issue by mupkoo** [jgwhite/ember-sortable#124] opened 2016-11-28 09:15 UTC
Whenever there is an input inside of a sortable group, you cannot focus on it with a click. But you can do it with a second click.

Here you can find a demo:
https://ember-twiddle.com/e97d74aafeaee76e246426cca3b6197e?openFiles=templates.application.hbs%2C

**Comment by jgwhite** [comment] 2016-11-28 09:53
Thanks for your feedback.

For this use case, I generally recommend using the `handle` attr, as seen in the readme:

```hbs
{{#sortable-item tagName="li" model=item group=group handle=".handle"}}
  {{item.name}}
  <span class="handle">&varr;</span>
{{/sortable-item}}
```

Here’s the concept applied to your example:

https://ember-twiddle.com/90ede70dfb4a3f00b12ea261fd7eb6d8?openFiles=templates.application.hbs%2C

**Comment by acburdine** [comment] 2016-11-28 14:45
@mupkoo as @jgwhite, the correct way to do this is to use the `handle` attr. Closing this as it is intended behavior.

**Closed by acburdine** 2016-11-28 14:45 UTC

**Comment by nagytezsolt** [comment] 2018-10-10 12:11
Current behavior: if the input is inside the "handler" the input is not focusable, only with mouse right click
{{#sortable-group tagName="ul" onChange="reorder" as |group|}}
  {{#each colors as |color|}}
    {{#sortable-item tagName="li" model=color group=group  handle=".handle"}}
    	<div  class="handle">
      	{{ input value=color }}
      </div>
      
    {{/sortable-item}}
  {{/each}}
{{/sortable-group}}
